import { Inter } from "next/font/google";
import 'animate.css';
import "./globals.css";
import Header from "@/components/Header";
import Navbar from "@/components/Nav";
import Footer from "@/components/Footer"
const inter = Inter({ subsets: ["latin"] });
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import TawkToScript from "@/components/TawkToScript";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        <Navbar/>
        {children}
        </body>
        <TawkToScript />
        <Footer/>
    </html>
  );
}
